/* =====================================================
   TAROT CARDS - the whole deck, all 78
   (tarot.html uses this, the moving parts are in tarot.js)

   every card has an upright side and a reversed (upside down) side.
   each side has:
     keywords = three words/phrases that sum it up
     meaning  = what the card means in general
     past / present / future / advice
              = what it says depending on where it lands in the spread.
                tarot.js picks the line that matches the spot

   reversed is NOT just "the opposite". it's the same card but blocked,
   turned inward or overdone. and for the scary cards (tower, devil,
   three of swords...) reversed usually means it's easing off.

   id = also the picture's file name -> images/tarot/<id>.jpg
   so when i draw my own cards: save each drawing over the pic with the same id
   (the card back is images/tarot/back.svg)

   i can rewrite any line here in my own words, just keep the quotes "" and the commas.

   meanings are based on Waite's Pictorial Key to the Tarot (1910)
   + how the cards are usually read these days
   ===================================================== */

const TAROT_CARDS = [

  /* ---------- MAJOR ARCANA - the big themes (The Fool to The World) ---------- */

  {
    id: "major-00",
    name: "The Fool",
    suit: "major",
    upright: {
      keywords: "beginnings, a leap of faith, openness",
      meaning:  "A fresh start taken on trust, before you know how it will turn out.",
      past:     "You set off on something new without a map, and that leap is why you're here.",
      present:  "You're at the very start of something, with more curiosity than experience.",
      future:   "A new beginning is coming, and it will ask you to jump before you feel ready.",
      advice:   "Say yes and start. You can learn the rest on the way.",
    },
    reversed: {
      keywords: "recklessness, hesitation, a false start",
      meaning:  "The leap gone wrong: rushing in without looking, or being too afraid to jump at all.",
      past:     "You either leapt carelessly or held back out of fear, and you're still feeling it.",
      present:  "You're frozen at the edge, or about to do something without thinking it through.",
      future:   "A chance to start over will come. Take care that you neither freeze nor rush it.",
      advice:   "Look before you leap, but do leap.",
    },
  },
  {
    id: "major-01",
    name: "The Magician",
    suit: "major",
    upright: {
      keywords: "skill, willpower, making it happen",
      meaning:  "Having everything you need on the table, and the will to turn an idea into something real.",
      past:     "You used what you had and made something happen through your own skill.",
      present:  "The tools are all in front of you. This is the moment to act.",
      future:   "You'll soon be in a position to make something real out of an idea.",
      advice:   "Stop preparing and use what you already have.",
    },
    reversed: {
      keywords: "unused talent, trickery, scattered focus",
      meaning:  "Ability going unused or being misused, through doubt, distraction or a bit of deceit.",
      past:     "You had the ability and didn't use it, or someone wasn't straight with you.",
      present:  "Your energy is scattered, or something here isn't what it's made out to be.",
      future:   "Watch for big promises that don't hold up, including the ones you make yourself.",
      advice:   "Pick one thing, and be honest about what you can actually do.",
    },
  },
  {
    id: "major-02",
    name: "The High Priestess",
    suit: "major",
    upright: {
      keywords: "intuition, mystery, inner knowing",
      meaning:  "Quiet knowledge below the surface: trusting what you sense before you can explain it.",
      past:     "You knew something before you could prove it, and you were right to listen.",
      present:  "Not everything is visible yet. Your gut already knows more than the facts do.",
      future:   "Something hidden will come to light, and your instinct will recognise it first.",
      advice:   "Be still and listen to yourself before asking anyone else.",
    },
    reversed: {
      keywords: "ignored instincts, secrets, surface noise",
      meaning:  "Being cut off from your own intuition, or a secret that has been kept too long.",
      past:     "You talked yourself out of what you sensed, or something was kept from you.",
      present:  "You're listening to everyone but yourself right now.",
      future:   "A secret won't stay hidden much longer.",
      advice:   "Stop second-guessing the feeling you keep pushing away.",
    },
  },
  {
    id: "major-03",
    name: "The Empress",
    suit: "major",
    upright: {
      keywords: "abundance, nurture, creativity",
      meaning:  "Growth, comfort and plenty: things flourishing because they're being cared for.",
      past:     "You were well looked after, or you poured care into something and it grew.",
      present:  "This is a fertile time. What you tend now will thrive.",
      future:   "A season of comfort and creative growth is on its way.",
      advice:   "Take care of it, and of yourself, and let it grow at its own pace.",
    },
    reversed: {
      keywords: "creative block, neglect, smothering",
      meaning:  "Care out of balance: neglecting yourself, drying up creatively, or holding on too tight.",
      past:     "You gave so much to others that little was left for yourself.",
      present:  "You're running on empty, or smothering something that needs room.",
      future:   "A dry spell is coming unless you make time to refill.",
      advice:   "Look after yourself first. The work will follow.",
    },
  },
  {
    id: "major-04",
    name: "The Emperor",
    suit: "major",
    upright: {
      keywords: "structure, authority, stability",
      meaning:  "Order, discipline and firm foundations: taking charge and setting the rules.",
      past:     "Structure and discipline, yours or someone else's, shaped where you are now.",
      present:  "The situation needs a plan and someone to lead. That someone may be you.",
      future:   "Things will settle into a firmer, more stable shape.",
      advice:   "Set boundaries, make a plan and stick to it.",
    },
    reversed: {
      keywords: "rigidity, control, no discipline",
      meaning:  "Authority gone sour: too controlling, too stubborn, or no structure at all.",
      past:     "Someone's need for control, or a lack of any order, made things harder.",
      present:  "You're gripping too tightly, or avoiding the discipline this needs.",
      future:   "A power struggle is likely unless someone loosens up.",
      advice:   "Ease your grip where you're rigid, and add structure where there's none.",
    },
  },
  {
    id: "major-05",
    name: "The Hierophant",
    suit: "major",
    upright: {
      keywords: "tradition, teaching, belonging",
      meaning:  "Learning from established ways, teachers and shared beliefs. Doing it by the book.",
      past:     "You followed the accepted path, or a teacher or tradition shaped you.",
      present:  "The conventional route is the right one for now. Learn from those who know.",
      future:   "A mentor, a course or an institution will play a part in what comes next.",
      advice:   "Learn the rules properly before you decide which ones to break.",
    },
    reversed: {
      keywords: "rebellion, questioning, your own way",
      meaning:  "Breaking from convention: questioning what you were taught and making your own rules.",
      past:     "You pushed back against what was expected of you.",
      present:  "The usual way doesn't fit you any more, and you know it.",
      future:   "You'll find yourself leaving a set path to do things your own way.",
      advice:   "Question the rule that's holding you back. You don't need permission.",
    },
  },
  {
    id: "major-06",
    name: "The Lovers",
    suit: "major",
    upright: {
      keywords: "love, harmony, a choice from the heart",
      meaning:  "A real connection, and a choice made in line with what you truly value.",
      past:     "A relationship or a heartfelt choice set you on this path.",
      present:  "You're in step with someone, or facing a choice that shows what you value.",
      future:   "A meaningful bond, or a choice between two paths, is coming.",
      advice:   "Choose what you love, not what merely looks sensible.",
    },
    reversed: {
      keywords: "disharmony, mixed values, avoiding a choice",
      meaning:  "Being out of step with someone or with yourself. A choice dodged, or made for the wrong reasons.",
      past:     "A bond fell out of balance, or you chose against your own heart.",
      present:  "What you want and what you're doing don't match right now.",
      future:   "A relationship or a decision will be tested. Half-measures won't hold.",
      advice:   "Be honest about what you actually want before you commit.",
    },
  },
  {
    id: "major-07",
    name: "The Chariot",
    suit: "major",
    upright: {
      keywords: "willpower, drive, victory",
      meaning:  "Winning through focus and determination: holding opposing forces together and moving forward.",
      past:     "You pushed through by sheer will and got where you meant to go.",
      present:  "You're in the driver's seat. Stay focused and keep moving.",
      future:   "Success is coming through effort and a firm hand on the reins.",
      advice:   "Decide where you're going and don't let yourself be pulled aside.",
    },
    reversed: {
      keywords: "lost direction, forcing it, stalled",
      meaning:  "Drive without direction: spinning your wheels, or pushing so hard you lose control.",
      past:     "You lost your grip on where things were heading, or forced what wasn't ready.",
      present:  "You're being pulled two ways and getting nowhere.",
      future:   "Progress will stall until you choose a direction.",
      advice:   "Stop pushing. Work out where you actually want to go, then start again.",
    },
  },
  {
    id: "major-08",
    name: "Strength",
    suit: "major",
    upright: {
      keywords: "courage, patience, gentle power",
      meaning:  "Quiet inner strength: taming something difficult with patience and kindness, not force.",
      past:     "You got through something hard with patience instead of force.",
      present:  "You have more courage than you think, and gentleness is how to use it.",
      future:   "You'll meet a challenge and handle it calmly.",
      advice:   "Be patient and kind with it, and with yourself most of all.",
    },
    reversed: {
      keywords: "self-doubt, forcing, raw nerves",
      meaning:  "Confidence run low, or trying to overpower what needs a gentler hand.",
      past:     "You doubted yourself, or let your temper do the talking.",
      present:  "Your confidence is shaky and you're being hard on yourself.",
      future:   "Your patience will be tested, and you may feel less sure of yourself for a while.",
      advice:   "Stop fighting yourself. Go gently until your nerve comes back.",
    },
  },
  {
    id: "major-09",
    name: "The Hermit",
    suit: "major",
    upright: {
      keywords: "solitude, looking inward, your own light",
      meaning:  "Stepping back from the noise to think, and finding your own answers.",
      past:     "You withdrew for a while, and what you worked out alone still guides you.",
      present:  "You need quiet more than company. The answer is inside, not out there.",
      future:   "A stretch of chosen solitude is coming, and it will make things clearer.",
      advice:   "Take time alone with this before asking anyone else.",
    },
    reversed: {
      keywords: "isolation, loneliness, hiding away",
      meaning:  "Solitude gone too far, into loneliness. Or the opposite: refusing the quiet you need.",
      past:     "You were more cut off than was good for you, and it left a mark.",
      present:  "You're more alone than you want to be, or hiding from people.",
      future:   "A lonely stretch is likely if you keep everyone at a distance.",
      advice:   "Reach out. You've been alone with this long enough.",
    },
  },
  {
    id: "major-10",
    name: "Wheel of Fortune",
    suit: "major",
    upright: {
      keywords: "change, luck, a turning point",
      meaning:  "Life's cycles turning: a change of luck you didn't cause and can't fully control.",
      past:     "Luck turned, and a change you didn't plan put you on this road.",
      present:  "Things are shifting. You're at a turning point.",
      future:   "A stroke of fortune or a sudden change is on its way.",
      advice:   "Go with the turn. It's moving whether you agree or not.",
    },
    reversed: {
      keywords: "bad luck, resisting change, a stuck cycle",
      meaning:  "The wheel turning against you, or a pattern that keeps repeating because you won't let it change.",
      past:     "A run of bad luck, or the same pattern on repeat, held you back.",
      present:  "You're resisting a change that is happening anyway.",
      future:   "A setback is likely, but the wheel doesn't stay down.",
      advice:   "Stop clinging to how things were, and break the cycle yourself.",
    },
  },
  {
    id: "major-11",
    name: "Justice",
    suit: "major",
    upright: {
      keywords: "fairness, truth, cause and effect",
      meaning:  "Honest consequences: what you did comes back as it deserves, and decisions are made fairly.",
      past:     "You got what was fair, and a clear-headed decision set things straight.",
      present:  "This calls for honesty and a level head. The truth matters here.",
      future:   "A fair outcome is coming. You'll get what you've earned.",
      advice:   "Be truthful, weigh both sides, and own your part.",
    },
    reversed: {
      keywords: "unfairness, dodging blame, bias",
      meaning:  "The scales out of balance: an unfair outcome, or someone refusing to take responsibility.",
      past:     "You were treated unfairly, or someone didn't own up.",
      present:  "Something here isn't being judged honestly, maybe by you.",
      future:   "A decision may not go the way it should. Be ready to argue your side.",
      advice:   "Stop making excuses and look at your own share of it.",
    },
  },
  {
    id: "major-12",
    name: "The Hanged Man",
    suit: "major",
    upright: {
      keywords: "pause, surrender, a new angle",
      meaning:  "A willing pause: letting go of control and seeing things from a different angle.",
      past:     "A time of waiting changed how you saw everything.",
      present:  "You're in limbo, and that's fine. Nothing needs forcing.",
      future:   "A pause is coming that will change your point of view.",
      advice:   "Stop struggling, wait, and look at it upside down.",
    },
    reversed: {
      keywords: "stalling, stuck, resisting the pause",
      meaning:  "Waiting with nothing gained: stalling, or fighting a pause instead of learning from it.",
      past:     "You stayed stuck too long, or gave things up and got nothing back.",
      present:  "You're putting off a decision and calling it patience.",
      future:   "A delay will drag on unless you change your approach.",
      advice:   "You've waited enough. Make the move.",
    },
  },
  {
    id: "major-13",
    name: "Death",
    suit: "major",
    upright: {
      keywords: "endings, change, letting go",
      meaning:  "An ending that clears the ground for something new. It's rarely about actual death.",
      past:     "Something ended for good, and that ending made room for now.",
      present:  "A chapter is closing. Let it.",
      future:   "An ending is coming, and something new is right behind it.",
      advice:   "Let go of what's finished so the next thing can start.",
    },
    reversed: {
      keywords: "resisting an ending, stagnation, holding on",
      meaning:  "Clinging to what's already over, and staying stuck because of it.",
      past:     "You held on to something past its time.",
      present:  "You're refusing an ending that needs to happen.",
      future:   "Change will keep knocking until you let it in.",
      advice:   "Stop propping it up. Let it end.",
    },
  },
  {
    id: "major-14",
    name: "Temperance",
    suit: "major",
    upright: {
      keywords: "balance, patience, blending",
      meaning:  "Moderation and the right mix: combining things slowly until they work together.",
      past:     "Patience and a steady middle way got you through.",
      present:  "Things are in balance. Keep the mix as it is and don't rush.",
      future:   "Calm is coming, and things that didn't fit will start to blend.",
      advice:   "Go slowly and take a little of each. No extremes.",
    },
    reversed: {
      keywords: "imbalance, excess, impatience",
      meaning:  "Too much of one thing and too little of another: rushing, overdoing, falling out of rhythm.",
      past:     "You overdid something, or rushed what needed time.",
      present:  "Something in your life is out of proportion right now.",
      future:   "Burnout or a clash is likely unless you slow down.",
      advice:   "Cut back on what you're overdoing and get the balance back.",
    },
  },
  {
    id: "major-15",
    name: "The Devil",
    suit: "major",
    upright: {
      keywords: "attachment, temptation, feeling trapped",
      meaning:  "Being tied to something that isn't good for you. The chains are looser than they look.",
      past:     "A habit, a fear or a bad deal had a hold on you.",
      present:  "You feel trapped, but much of this cage is your own doing.",
      future:   "A temptation is coming that will be easy to say yes to.",
      advice:   "Name what has a hold on you. That's the first step out.",
    },
    reversed: {
      keywords: "breaking free, release, facing the shadow",
      meaning:  "Loosening the grip of something that had you: seeing the chain and taking it off.",
      past:     "You broke away from something that had a hold on you.",
      present:  "You're getting free of an old attachment, link by link.",
      future:   "You'll find the strength to walk away from what's been keeping you small.",
      advice:   "Keep going. Don't turn back for what you've just escaped.",
    },
  },
  {
    id: "major-16",
    name: "The Tower",
    suit: "major",
    upright: {
      keywords: "upheaval, sudden change, a truth revealed",
      meaning:  "Something built on shaky ground falling down all at once. Painful, but it clears away what was false.",
      past:     "Something collapsed without warning, and you've been rebuilding since.",
      present:  "Things are being shaken up. What falls now wasn't solid.",
      future:   "A sudden shake-up is coming. It will hurt less if you don't cling.",
      advice:   "Let it fall, then build on what's actually true.",
    },
    reversed: {
      keywords: "a near miss, delayed collapse, change from within",
      meaning:  "Disaster dodged or delayed: a shake-up happening inside you, or one you're still putting off.",
      past:     "You narrowly escaped a crisis, or put off one that was due.",
      present:  "You know something has to change, and you're holding the walls up anyway.",
      future:   "The upheaval will be smaller than you fear, if you stop resisting it.",
      advice:   "Take the wall down yourself before it falls on you.",
    },
  },
  {
    id: "major-17",
    name: "The Star",
    suit: "major",
    upright: {
      keywords: "hope, healing, calm after the storm",
      meaning:  "Hope returning after a hard time, and a quiet faith that things will get better.",
      past:     "After a rough stretch you found your hope again.",
      present:  "You're healing. Things are gentler now, and you can trust that.",
      future:   "Better days are coming, and you'll feel like yourself again.",
      advice:   "Keep faith and stay open. You're on the right path.",
    },
    reversed: {
      keywords: "lost hope, self-doubt, discouragement",
      meaning:  "Hope run dry: feeling discouraged and unable to see the light that is still there.",
      past:     "You lost faith for a while, in things or in yourself.",
      present:  "You're discouraged and can't see how this gets better. It still can.",
      future:   "Your faith will be tested, but the low point won't last.",
      advice:   "Do one small thing that reminds you what you're hoping for.",
    },
  },
  {
    id: "major-18",
    name: "The Moon",
    suit: "major",
    upright: {
      keywords: "illusion, uncertainty, dreams",
      meaning:  "Walking in half-light: things aren't what they seem, and fear and imagination fill the gaps.",
      past:     "You couldn't see clearly then, and fear or confusion led you.",
      present:  "Not everything is as it looks. Don't decide in the dark.",
      future:   "A confusing stretch is ahead where you'll have to feel your way.",
      advice:   "Wait for more light before you act, and notice what your fears are telling you.",
    },
    reversed: {
      keywords: "clarity returning, fears faced, the truth coming out",
      meaning:  "The fog lifting: confusion clearing, fears shrinking, something hidden coming into view.",
      past:     "A confusion cleared, and you saw what was really going on.",
      present:  "The fog is lifting. What frightened you is smaller than it seemed.",
      future:   "What's been unclear will soon make sense.",
      advice:   "Trust what you can now see, and let the old fear go.",
    },
  },
  {
    id: "major-19",
    name: "The Sun",
    suit: "major",
    upright: {
      keywords: "joy, success, warmth",
      meaning:  "Plain, uncomplicated happiness: success, energy, and everything out in the open.",
      past:     "You had a bright, happy time, and it still warms you.",
      present:  "Things are going well. Enjoy it without looking for the catch.",
      future:   "Good news and a happy stretch are on the way.",
      advice:   "Say yes, be seen, and let yourself enjoy it.",
    },
    reversed: {
      keywords: "dimmed joy, delays, forced cheer",
      meaning:  "The sun behind a cloud: still good, but dimmed, delayed, or hard to let in.",
      past:     "A good time was shadowed by something, or you couldn't enjoy it fully.",
      present:  "Things are fine, but you're not letting yourself feel it.",
      future:   "Success will come, but later or smaller than you hoped.",
      advice:   "Notice what's going right, and stop waiting for the perfect moment to be happy.",
    },
  },
  {
    id: "major-20",
    name: "Judgement",
    suit: "major",
    upright: {
      keywords: "awakening, reckoning, a calling",
      meaning:  "A wake-up call: looking honestly at the past, forgiving it, and answering what calls you next.",
      past:     "You had a moment of reckoning and came out of it changed.",
      present:  "You're being called to something. It's time to decide.",
      future:   "A moment of truth is coming that will ask you to step up.",
      advice:   "Answer the call. Forgive the past and move.",
    },
    reversed: {
      keywords: "self-doubt, ignoring the call, harsh self-judgement",
      meaning:  "Hearing the call and not answering, or judging yourself so harshly that you can't move on.",
      past:     "You ignored a call, or kept punishing yourself for an old mistake.",
      present:  "You know what you should do and you're avoiding it.",
      future:   "The same question will keep coming back until you answer it.",
      advice:   "Be kinder to yourself about the past, and stop putting off the decision.",
    },
  },
  {
    id: "major-21",
    name: "The World",
    suit: "major",
    upright: {
      keywords: "completion, wholeness, arrival",
      meaning:  "A cycle finished properly: the goal reached and everything coming together.",
      past:     "You finished something big, and it made you who you are now.",
      present:  "You're at the end of a long road. Take a moment to notice.",
      future:   "Completion is coming. You'll get there.",
      advice:   "Finish it properly, and celebrate before you start the next thing.",
    },
    reversed: {
      keywords: "loose ends, unfinished business, almost there",
      meaning:  "Nearly done but not quite: a loose end, a shortcut, or closure that hasn't come.",
      past:     "You left something unfinished, and it still follows you.",
      present:  "You're close, but one loose end is keeping this open.",
      future:   "The finish will take longer than planned. Don't cut corners.",
      advice:   "Go back and tie off the last loose end.",
    },
  },

  /* ---------- WANDS - drive, ideas, work ---------- */

  {
    id: "wands-01",
    name: "Ace of Wands",
    suit: "wands",
    upright: {
      keywords: "spark, inspiration, a new project",
      meaning:  "The first spark of an idea or a passion: raw energy that wants to become something.",
      past:     "A burst of inspiration started all this.",
      present:  "You've got a new idea and the energy to begin it.",
      future:   "A new spark is coming: a project, a passion, a reason to get up in the morning.",
      advice:   "Act on the idea while it's hot.",
    },
    reversed: {
      keywords: "false start, delay, low energy",
      meaning:  "A spark that won't catch: enthusiasm fizzling, or a start that keeps being put off.",
      past:     "Something you were excited about never really got going.",
      present:  "You want to begin, but the energy isn't there yet.",
      future:   "A start will be delayed. Don't force it before it's ready.",
      advice:   "Find what actually excites you before you pour effort in.",
    },
  },
  {
    id: "wands-02",
    name: "Two of Wands",
    suit: "wands",
    upright: {
      keywords: "planning, a decision, wider horizons",
      meaning:  "Holding the world in your hand and planning the next move: stay with the safe thing, or go further.",
      past:     "You made a plan and looked beyond what you already had.",
      present:  "You're weighing whether to stay put or go further.",
      future:   "You'll soon need to choose between the familiar and something bigger.",
      advice:   "Make the plan, then take the first step out the door.",
    },
    reversed: {
      keywords: "fear of the unknown, playing safe, poor planning",
      meaning:  "Staying home out of fear, with plans that never leave the page.",
      past:     "You played it safe and stayed where you were.",
      present:  "You're hesitating at the door, afraid of what's beyond it.",
      future:   "An opportunity will pass you by unless you plan for it.",
      advice:   "Stop over-thinking and commit to one direction.",
    },
  },
  {
    id: "wands-03",
    name: "Three of Wands",
    suit: "wands",
    upright: {
      keywords: "expansion, foresight, ships coming in",
      meaning:  "The first results of your plans arriving. Looking further ahead and thinking bigger.",
      past:     "Your early efforts paid off and opened things up.",
      present:  "Things are in motion. Your ships are on their way.",
      future:   "Progress and wider opportunities are coming, possibly from far away.",
      advice:   "Think bigger and keep watching the horizon.",
    },
    reversed: {
      keywords: "delays, setbacks, thinking small",
      meaning:  "Ships that are late: plans held up, or aiming smaller than you could.",
      past:     "Plans were delayed, or didn't go as far as you hoped.",
      present:  "You're waiting on something that's taking too long.",
      future:   "Expect delays before things open up.",
      advice:   "Check your plan for what you've overlooked, and be patient.",
    },
  },
  {
    id: "wands-04",
    name: "Four of Wands",
    suit: "wands",
    upright: {
      keywords: "celebration, home, a milestone",
      meaning:  "A happy pause: a milestone reached, people gathered, a feeling of home.",
      past:     "A celebration or a steady home gave you a good base.",
      present:  "There's something to celebrate, and you're among your people.",
      future:   "A happy gathering or a milestone is coming.",
      advice:   "Stop and mark the occasion with the people who matter.",
    },
    reversed: {
      keywords: "unsettled home, a postponed celebration, not belonging",
      meaning:  "The same joy, but unsettled: tension at home, a party put off, feeling a bit out of place.",
      past:     "Things at home were shaky, or a happy moment was cut short.",
      present:  "You don't feel quite settled or welcome where you are.",
      future:   "A celebration may be delayed, or a change at home is coming.",
      advice:   "Make your own sense of home, and don't wait for the perfect moment to celebrate.",
    },
  },
  {
    id: "wands-05",
    name: "Five of Wands",
    suit: "wands",
    upright: {
      keywords: "conflict, competition, friction",
      meaning:  "Everyone pulling a different way: rivalry, arguments and clashing ideas. More noise than harm.",
      past:     "You came through a time of rivalry and squabbling.",
      present:  "Too many opinions are clashing and nothing is getting done.",
      future:   "Expect some competition or disagreement ahead.",
      advice:   "Hold your own, but don't mistake a scrap for a war.",
    },
    reversed: {
      keywords: "avoiding conflict, tension easing, inner conflict",
      meaning:  "The fight winding down or being dodged, or the argument going on inside you instead.",
      past:     "A conflict was settled, or avoided when it should have been had.",
      present:  "You're keeping the peace by swallowing what you think.",
      future:   "The squabbling will die down.",
      advice:   "Say what you've been holding back, calmly.",
    },
  },
  {
    id: "wands-06",
    name: "Six of Wands",
    suit: "wands",
    upright: {
      keywords: "victory, recognition, pride",
      meaning:  "Success that other people can see: praise, a win, a moment in the spotlight.",
      past:     "You had a win and were recognised for it.",
      present:  "You're being noticed for what you've done. Enjoy it.",
      future:   "Recognition is coming for your efforts.",
      advice:   "Take the credit you've earned, and carry yourself like it.",
    },
    reversed: {
      keywords: "no recognition, self-doubt, a fall from grace",
      meaning:  "The win that goes unnoticed, or pride that has tipped into ego or a stumble.",
      past:     "Your work went unnoticed, or a win didn't last.",
      present:  "You feel overlooked, or you're doubting what you've achieved.",
      future:   "Praise may not come when you expect it. Do the work anyway.",
      advice:   "Stop waiting for applause and measure it by your own standard.",
    },
  },
  {
    id: "wands-07",
    name: "Seven of Wands",
    suit: "wands",
    upright: {
      keywords: "standing your ground, defence, persistence",
      meaning:  "Holding the high ground against pressure, and defending what you've built.",
      past:     "You had to fight to keep your position, and you held it.",
      present:  "You're being challenged. Stand firm, you have the advantage.",
      future:   "You'll need to defend something you care about.",
      advice:   "Don't back down. You earned this spot.",
    },
    reversed: {
      keywords: "overwhelmed, giving up, worn defences",
      meaning:  "Too many fronts to defend: feeling overwhelmed and tempted to give in.",
      past:     "You were worn down and gave ground.",
      present:  "You're overwhelmed and wondering if it's worth the fight.",
      future:   "The pressure will build. Choose which battles are yours.",
      advice:   "Drop the fights that don't matter and keep the one that does.",
    },
  },
  {
    id: "wands-08",
    name: "Eight of Wands",
    suit: "wands",
    upright: {
      keywords: "speed, movement, news",
      meaning:  "Everything moving at once: quick progress, messages, travel.",
      past:     "Things happened fast, and you were carried along.",
      present:  "Events are moving quickly. Keep up.",
      future:   "News is coming, and things will speed up.",
      advice:   "Act now, while it's moving.",
    },
    reversed: {
      keywords: "delays, waiting, crossed wires",
      meaning:  "Momentum lost: delays, mixed messages, hurrying up only to wait.",
      past:     "Things slowed to a crawl, or messages got crossed.",
      present:  "You're stuck waiting on something or someone.",
      future:   "Expect delays. It will take longer than promised.",
      advice:   "Be patient, and double-check what was actually said.",
    },
  },
  {
    id: "wands-09",
    name: "Nine of Wands",
    suit: "wands",
    upright: {
      keywords: "resilience, perseverance, guardedness",
      meaning:  "Battered but still standing: tired, wary, and nearly there.",
      past:     "You took some knocks and kept going.",
      present:  "You're weary and on guard, but you have one more push in you.",
      future:   "One more test is coming before the end, and you'll get through it.",
      advice:   "Hold on. You're closer than you think.",
    },
    reversed: {
      keywords: "exhaustion, defensiveness, giving in",
      meaning:  "Nothing left in the tank, and so guarded that you're keeping help out too.",
      past:     "You were worn out, and may have pushed people away.",
      present:  "You're exhausted and expecting the worst from everyone.",
      future:   "You'll hit a wall unless you rest.",
      advice:   "Lower your guard a little and let someone help.",
    },
  },
  {
    id: "wands-10",
    name: "Ten of Wands",
    suit: "wands",
    upright: {
      keywords: "burden, overload, responsibility",
      meaning:  "Carrying far too much by yourself: hard work that has become a weight.",
      past:     "You took on too much and carried it alone.",
      present:  "You're overloaded. This is more than one person's share.",
      future:   "The load will get heavier before you set it down, unless you share it.",
      advice:   "Put some of it down, or hand it to someone else.",
    },
    reversed: {
      keywords: "putting it down, release, buckling",
      meaning:  "Setting the burden down, by choice or because you can't hold it any longer.",
      past:     "You finally put down something heavy, or buckled under it.",
      present:  "You're learning to let go of what was never yours to carry.",
      future:   "Relief is coming. A weight will be lifted.",
      advice:   "Say no to the next thing, and mean it.",
    },
  },
  {
    id: "wands-11",
    name: "Page of Wands",
    suit: "wands",
    upright: {
      keywords: "curiosity, enthusiasm, a new idea",
      meaning:  "An eager beginner full of ideas: exciting news, or the urge to try something.",
      past:     "You were full of ideas and keen to explore.",
      present:  "Something has caught your interest. Follow it.",
      future:   "Exciting news or a fresh idea is on its way.",
      advice:   "Try it, just to see what happens.",
    },
    reversed: {
      keywords: "restlessness, half-baked plans, discouragement",
      meaning:  "Lots of ideas and no follow-through: enthusiasm that fizzles at the first obstacle.",
      past:     "You started things and dropped them.",
      present:  "You're restless but can't settle on anything.",
      future:   "A plan may fizzle unless you give it some structure.",
      advice:   "Pick one idea and see it through to the end.",
    },
  },
  {
    id: "wands-12",
    name: "Knight of Wands",
    suit: "wands",
    upright: {
      keywords: "action, adventure, boldness",
      meaning:  "Charging off after what excites you: passion, travel, fearless energy.",
      past:     "You threw yourself into something head first.",
      present:  "You're fired up and ready to go.",
      future:   "A burst of action or a sudden move is coming.",
      advice:   "Go for it, boldly.",
    },
    reversed: {
      keywords: "haste, recklessness, burning out",
      meaning:  "All charge and no plan: impulsive moves, flashes of temper, energy that burns out fast.",
      past:     "You rushed in and it didn't last.",
      present:  "You're being impatient, and it's making you careless.",
      future:   "A hasty move could backfire. Slow down.",
      advice:   "Count to ten before you leap.",
    },
  },
  {
    id: "wands-13",
    name: "Queen of Wands",
    suit: "wands",
    upright: {
      keywords: "confidence, warmth, independence",
      meaning:  "Sure of herself and generous with it: someone who lights up a room and gets things done.",
      past:     "You, or someone warm and bold, carried things with confidence.",
      present:  "You're in your element. Let people see it.",
      future:   "You'll step into your confidence, or meet someone who brings it out.",
      advice:   "Be bold and warm, and take up space.",
    },
    reversed: {
      keywords: "insecurity, jealousy, a short fuse",
      meaning:  "Confidence shaken: comparing, feeling small, or snapping at people to cover it.",
      past:     "You doubted yourself, or someone's jealousy got in the way.",
      present:  "You're comparing yourself to others and coming off worse.",
      future:   "Your confidence will wobble. Don't take it out on anyone.",
      advice:   "Stop measuring yourself against other people.",
    },
  },
  {
    id: "wands-14",
    name: "King of Wands",
    suit: "wands",
    upright: {
      keywords: "leadership, vision, getting people moving",
      meaning:  "A natural leader with a big idea and the nerve to carry it out.",
      past:     "You, or a bold leader, set a vision and others followed.",
      present:  "It's yours to lead. People are looking to you.",
      future:   "You'll be asked to take charge of something.",
      advice:   "Lead from the front and hold to the vision.",
    },
    reversed: {
      keywords: "bossiness, impulsiveness, big talk",
      meaning:  "Leadership gone overbearing: demanding, hasty, promising more than gets delivered.",
      past:     "Someone was overbearing, or big promises came to little.",
      present:  "You're pushing people too hard, or being pushed.",
      future:   "Watch for a domineering figure, or for becoming one.",
      advice:   "Listen before you give orders.",
    },
  },

  /* ---------- CUPS - feelings, relationships ---------- */

  {
    id: "cups-01",
    name: "Ace of Cups",
    suit: "cups",
    upright: {
      keywords: "new feeling, love, an open heart",
      meaning:  "The heart filling up: a new love, a friendship, or a wave of feeling.",
      past:     "A new love or a deep feeling opened you up.",
      present:  "Your heart is full. Let it show.",
      future:   "New love, friendship or joy is coming.",
      advice:   "Open up and let yourself feel it.",
    },
    reversed: {
      keywords: "bottled-up feelings, emptiness, a closed heart",
      meaning:  "Feelings held in or drained away: a heart that's shut, or running on empty.",
      past:     "You bottled things up, or felt emptied out.",
      present:  "You're holding your feelings in.",
      future:   "You may feel flat for a while. Look after yourself.",
      advice:   "Let it out, and fill your own cup first.",
    },
  },
  {
    id: "cups-02",
    name: "Two of Cups",
    suit: "cups",
    upright: {
      keywords: "partnership, attraction, mutual respect",
      meaning:  "Two people meeting as equals: a bond of love, friendship or partnership.",
      past:     "A close bond was formed, and it mattered.",
      present:  "You have a real connection with someone, on equal footing.",
      future:   "A partnership or a mutual attraction is coming.",
      advice:   "Meet them halfway.",
    },
    reversed: {
      keywords: "imbalance, a falling-out, mistrust",
      meaning:  "A bond out of balance: one giving more than the other, a quarrel, trust wearing thin.",
      past:     "A relationship fell out of balance or broke off.",
      present:  "You and someone close are out of step.",
      future:   "A misunderstanding with someone close is likely. Talk early.",
      advice:   "Say the honest thing and repair it, or let it go.",
    },
  },
  {
    id: "cups-03",
    name: "Three of Cups",
    suit: "cups",
    upright: {
      keywords: "friendship, celebration, community",
      meaning:  "Raising a glass with your people: friends, good times, something to celebrate.",
      past:     "Friends and good times carried you.",
      present:  "You're surrounded by people who are glad for you.",
      future:   "A get-together, or good news to share, is coming.",
      advice:   "Call your friends and celebrate with them.",
    },
    reversed: {
      keywords: "overindulgence, gossip, drifting apart",
      meaning:  "Too much of a good time, or friends growing apart. Whispers and third wheels.",
      past:     "A friendship drifted, or there was gossip in the group.",
      present:  "You feel left out, or you're overdoing the fun.",
      future:   "A social plan may fall through, or your circle may shift.",
      advice:   "Step back from the crowd and spend time with the ones who count.",
    },
  },
  {
    id: "cups-04",
    name: "Four of Cups",
    suit: "cups",
    upright: {
      keywords: "apathy, boredom, a missed offer",
      meaning:  "Staring at what you have and feeling flat, while something new is held out unnoticed.",
      past:     "You were bored or withdrawn, and let an offer pass.",
      present:  "You're so fed up that you can't see what's in front of you.",
      future:   "A dull patch is coming. Look up, or you'll miss what's offered.",
      advice:   "Look up. There's something here you haven't noticed.",
    },
    reversed: {
      keywords: "fresh interest, waking up, saying yes",
      meaning:  "Coming out of a slump: noticing the offer and feeling interested again.",
      past:     "You shook off a slump and joined in again.",
      present:  "You're waking up to new possibilities.",
      future:   "Your interest will return, along with a new offer.",
      advice:   "Say yes to the next thing that's offered.",
    },
  },
  {
    id: "cups-05",
    name: "Five of Cups",
    suit: "cups",
    upright: {
      keywords: "loss, regret, grief",
      meaning:  "Mourning what was spilled, and not yet seeing what's still standing.",
      past:     "You lost something, and it grieved you.",
      present:  "You're fixed on what went wrong.",
      future:   "A disappointment is coming, but not everything will be lost.",
      advice:   "Grieve it, then turn around and see what's left.",
    },
    reversed: {
      keywords: "acceptance, moving on, forgiveness",
      meaning:  "Grief easing: picking up what remains and crossing the bridge.",
      past:     "You came through a loss and began to accept it.",
      present:  "You're starting to move on.",
      future:   "You'll make your peace with a loss.",
      advice:   "Forgive yourself and pick up what remains.",
    },
  },
  {
    id: "cups-06",
    name: "Six of Cups",
    suit: "cups",
    upright: {
      keywords: "nostalgia, memories, innocence",
      meaning:  "The sweetness of the past: childhood, old friends, simple kindness.",
      past:     "Happy memories and old ties shaped you.",
      present:  "The past is visiting: a memory, an old friend, a familiar place.",
      future:   "Someone or something from your past will return.",
      advice:   "Go back to what made you happy as a child.",
    },
    reversed: {
      keywords: "stuck in the past, rose-tinted memories, growing up",
      meaning:  "Living in memories instead of now, or finally letting the past be the past.",
      past:     "You held on to the past longer than was good for you.",
      present:  "You're looking backwards too much.",
      future:   "You'll have to leave something familiar behind.",
      advice:   "Keep the memory and let go of the rest.",
    },
  },
  {
    id: "cups-07",
    name: "Seven of Cups",
    suit: "cups",
    upright: {
      keywords: "choices, daydreams, illusion",
      meaning:  "So many tempting options that it's hard to tell the real from the wishful.",
      past:     "You were dazzled by options and built castles in the air.",
      present:  "You have many choices and no idea which are real.",
      future:   "You'll be offered a lot, and not all of it will be what it seems.",
      advice:   "Pick one, and check it's real before you chase it.",
    },
    reversed: {
      keywords: "clarity, a decision, back to reality",
      meaning:  "The daydream clearing: seeing what's real and finally choosing.",
      past:     "You stopped dreaming and made a choice.",
      present:  "Your head is clearing. You know what you actually want.",
      future:   "Things will come into focus and the choice will be obvious.",
      advice:   "Choose, and commit to it.",
    },
  },
  {
    id: "cups-08",
    name: "Eight of Cups",
    suit: "cups",
    upright: {
      keywords: "walking away, searching, moving on",
      meaning:  "Leaving behind something that no longer fills you, to look for something that does.",
      past:     "You walked away from something that wasn't enough.",
      present:  "You know it's time to leave something behind.",
      future:   "You'll turn your back on something to look for more.",
      advice:   "Go. You already know it isn't enough.",
    },
    reversed: {
      keywords: "staying put, fear of leaving, drifting",
      meaning:  "Knowing you should go and staying anyway, or wandering without knowing what you want.",
      past:     "You stayed when you wanted to go, or left and came back.",
      present:  "You're torn between leaving and staying.",
      future:   "You'll be tempted to go back to something you had left.",
      advice:   "Be honest about whether you're staying out of love or out of fear.",
    },
  },
  {
    id: "cups-09",
    name: "Nine of Cups",
    suit: "cups",
    upright: {
      keywords: "satisfaction, a wish granted, contentment",
      meaning:  "The wish card: getting what you wanted, and enjoying it.",
      past:     "You got what you wished for.",
      present:  "You have what you need. Enjoy it.",
      future:   "A wish is about to come true.",
      advice:   "Enjoy what you have, and say thank you.",
    },
    reversed: {
      keywords: "dissatisfaction, smugness, an empty wish",
      meaning:  "Getting what you wanted and still feeling something is missing, or overdoing the pleasure.",
      past:     "You got what you wanted and it didn't satisfy.",
      present:  "You have plenty and still feel something's lacking.",
      future:   "A wish may come true in a way that leaves you wanting.",
      advice:   "Ask what you actually want, underneath the wanting.",
    },
  },
  {
    id: "cups-10",
    name: "Ten of Cups",
    suit: "cups",
    upright: {
      keywords: "happiness, family, harmony",
      meaning:  "Emotional fulfilment: a happy home, people you love, peace.",
      past:     "You knew real happiness with the people around you.",
      present:  "You're loved and at home.",
      future:   "Lasting happiness at home is ahead.",
      advice:   "Put your people first.",
    },
    reversed: {
      keywords: "a strained home, broken harmony, a cracked ideal",
      meaning:  "Tension where there should be peace: a family or a dream that isn't living up to the picture.",
      past:     "There was strain at home, or a dream of happiness fell short.",
      present:  "Things look fine from outside, but something's off at home.",
      future:   "A family tension will need attention.",
      advice:   "Have the conversation you've all been avoiding.",
    },
  },
  {
    id: "cups-11",
    name: "Page of Cups",
    suit: "cups",
    upright: {
      keywords: "a tender message, imagination, a crush",
      meaning:  "A gentle dreamer: a sweet surprise, a creative idea, the first stir of feeling.",
      past:     "A sweet surprise or a creative spark touched you.",
      present:  "You're feeling tender and imaginative.",
      future:   "A loving message or a creative idea is on its way.",
      advice:   "Follow the whim and make something just for the joy of it.",
    },
    reversed: {
      keywords: "moodiness, daydreaming, bruised feelings",
      meaning:  "Feelings running the show: sulking, escaping into fantasy, taking things to heart.",
      past:     "You were easily hurt, or hid in daydreams.",
      present:  "You're being a bit moody and over-sensitive.",
      future:   "A small disappointment may sting more than it should.",
      advice:   "Don't take it so personally.",
    },
  },
  {
    id: "cups-12",
    name: "Knight of Cups",
    suit: "cups",
    upright: {
      keywords: "romance, an invitation, following the heart",
      meaning:  "The romantic on a white horse: an offer, a proposal, a gesture from the heart.",
      past:     "Someone, maybe you, followed their heart or made a romantic offer.",
      present:  "You're being led by your feelings, and it's lovely.",
      future:   "An invitation or a romantic gesture is coming.",
      advice:   "Make the offer. Say how you feel.",
    },
    reversed: {
      keywords: "empty promises, moodiness, unrealistic romance",
      meaning:  "All charm and no follow-through: promises that fade, feelings that change with the weather.",
      past:     "A lovely promise came to nothing.",
      present:  "You, or someone, are more in love with the idea than the reality.",
      future:   "An offer may sound better than it is.",
      advice:   "Check the facts behind the pretty words.",
    },
  },
  {
    id: "cups-13",
    name: "Queen of Cups",
    suit: "cups",
    upright: {
      keywords: "compassion, intuition, emotional depth",
      meaning:  "Deeply feeling and deeply kind: someone who understands without being told.",
      past:     "Kindness and intuition, yours or someone's, held things together.",
      present:  "You're tuned in to how everyone feels. Trust it.",
      future:   "You'll be the one others turn to for comfort, or you'll find someone who is.",
      advice:   "Lead with empathy, and trust what you feel.",
    },
    reversed: {
      keywords: "overwhelmed by feeling, over-giving, moodiness",
      meaning:  "Feeling too much: drowning in emotion, or giving until nothing is left.",
      past:     "You were swamped by feeling, or gave too much away.",
      present:  "You're absorbing everyone's emotions, and it's wearing you out.",
      future:   "You'll feel overwhelmed unless you set a limit.",
      advice:   "Protect your own heart before tending everyone else's.",
    },
  },
  {
    id: "cups-14",
    name: "King of Cups",
    suit: "cups",
    upright: {
      keywords: "calm, emotional balance, wise counsel",
      meaning:  "Steady in rough water: feeling deeply, but staying calm and kind.",
      past:     "You, or someone steady, kept calm through strong feelings.",
      present:  "You're in command of your emotions, and others can lean on you.",
      future:   "You'll handle an emotional situation calmly.",
      advice:   "Stay calm and be the steady one.",
    },
    reversed: {
      keywords: "moodiness, bottling up, manipulation",
      meaning:  "Calm on top and a storm underneath: feelings pushed down, or used to steer people.",
      past:     "Feelings were bottled up, or someone played on yours.",
      present:  "You're holding it together on the outside only.",
      future:   "Pent-up feeling will find its way out.",
      advice:   "Admit what you feel instead of managing everyone.",
    },
  },

  /* ---------- SWORDS - thinking, truth, conflict ---------- */

  {
    id: "swords-01",
    name: "Ace of Swords",
    suit: "swords",
    upright: {
      keywords: "clarity, truth, a breakthrough",
      meaning:  "A mind suddenly clear: a new idea, a truth, the cut that settles it.",
      past:     "A moment of clarity cut through the confusion.",
      present:  "You see it clearly now.",
      future:   "A breakthrough or a plain truth is coming.",
      advice:   "Say it plainly and decide.",
    },
    reversed: {
      keywords: "confusion, muddled thinking, harsh words",
      meaning:  "The blade turned the wrong way: muddle, a truth held back, words that wound.",
      past:     "You were confused, or something true wasn't said.",
      present:  "Your thinking is clouded right now.",
      future:   "Expect some confusion. Wait before deciding.",
      advice:   "Get your facts straight before you speak.",
    },
  },
  {
    id: "swords-02",
    name: "Two of Swords",
    suit: "swords",
    upright: {
      keywords: "indecision, stalemate, not looking",
      meaning:  "Blindfolded between two choices: avoiding a decision by refusing to look at it.",
      past:     "You couldn't choose, and stayed stuck.",
      present:  "You're avoiding a decision.",
      future:   "You'll face a choice you'd rather not make.",
      advice:   "Take off the blindfold and look at both options.",
    },
    reversed: {
      keywords: "a decision made, overload, the truth let in",
      meaning:  "The stalemate breaking: finally choosing, or being flooded with too much to weigh.",
      past:     "A deadlock broke and you had to choose.",
      present:  "You can't sit on the fence any longer.",
      future:   "The decision will be made, by you or for you.",
      advice:   "Choose. Any choice is better than this stalemate.",
    },
  },
  {
    id: "swords-03",
    name: "Three of Swords",
    suit: "swords",
    upright: {
      keywords: "heartbreak, sorrow, a painful truth",
      meaning:  "The heart pierced: grief, a break-up, words that hurt because they're true.",
      past:     "You had your heart broken.",
      present:  "You're hurting, and it's real.",
      future:   "A painful truth is coming. It will pass.",
      advice:   "Let yourself feel it. There's no way round, only through.",
    },
    reversed: {
      keywords: "healing, forgiveness, pain easing",
      meaning:  "The swords coming out: grief easing and the wound starting to heal.",
      past:     "You began to heal from an old hurt.",
      present:  "The pain is easing.",
      future:   "You'll get over this, and forgiveness will come.",
      advice:   "Let it go. You've carried it long enough.",
    },
  },
  {
    id: "swords-04",
    name: "Four of Swords",
    suit: "swords",
    upright: {
      keywords: "rest, recovery, stillness",
      meaning:  "Laying down the swords to rest: a pause to recover before going on.",
      past:     "You took time out to recover.",
      present:  "You need rest more than anything.",
      future:   "A quiet spell is coming. Take it.",
      advice:   "Stop and rest. Nothing will fall apart.",
    },
    reversed: {
      keywords: "restlessness, burnout, back to the fray",
      meaning:  "Rest refused, or rest over: pushing on when worn out, or getting up after a long stillness.",
      past:     "You pushed on without resting, and paid for it.",
      present:  "You're running on empty and won't stop.",
      future:   "You'll be back in action soon. Make sure you're ready.",
      advice:   "Rest properly before you burn out.",
    },
  },
  {
    id: "swords-05",
    name: "Five of Swords",
    suit: "swords",
    upright: {
      keywords: "conflict, a hollow win, bad blood",
      meaning:  "Winning the argument and losing the people: a fight where nobody comes out well.",
      past:     "There was a fight where someone won and everyone lost.",
      present:  "You're in a conflict that isn't worth winning.",
      future:   "An argument is coming. Think about what winning will cost.",
      advice:   "Walk away. Being right isn't worth this.",
    },
    reversed: {
      keywords: "making peace, regret, moving past it",
      meaning:  "The fight ending: apologies, regrets, and a wish to put it behind you.",
      past:     "A conflict ended, with some regret left over.",
      present:  "You want to make peace.",
      future:   "An old quarrel will be settled.",
      advice:   "Apologise, or accept the apology.",
    },
  },
  {
    id: "swords-06",
    name: "Six of Swords",
    suit: "swords",
    upright: {
      keywords: "transition, moving on, calmer waters",
      meaning:  "Crossing from rough water to calm: leaving trouble behind, quietly.",
      past:     "You left a hard situation behind.",
      present:  "You're in between, heading for somewhere calmer.",
      future:   "A move away from trouble is coming.",
      advice:   "Go, and don't look back at the rough water.",
    },
    reversed: {
      keywords: "stuck, baggage, a rough crossing",
      meaning:  "A crossing that won't start, or old baggage coming along with you.",
      past:     "You couldn't leave something behind, or took it with you.",
      present:  "You're resisting a change you need.",
      future:   "Moving on will be harder than expected.",
      advice:   "Put down what you don't need to bring.",
    },
  },
  {
    id: "swords-07",
    name: "Seven of Swords",
    suit: "swords",
    upright: {
      keywords: "secrecy, strategy, getting away with it",
      meaning:  "Slipping away with something: deceit, cunning, or doing things the sly way.",
      past:     "Someone wasn't honest, perhaps you.",
      present:  "Something is being done behind someone's back.",
      future:   "Watch for a trick, or the temptation to use one.",
      advice:   "Be clever, but ask yourself whether this is honest.",
    },
    reversed: {
      keywords: "coming clean, getting caught, conscience",
      meaning:  "The secret out: confessing, being found out, or deciding to stop sneaking.",
      past:     "A secret came out, or you came clean.",
      present:  "You're tired of hiding something.",
      future:   "The truth will come out.",
      advice:   "Own up before you're found out.",
    },
  },
  {
    id: "swords-08",
    name: "Eight of Swords",
    suit: "swords",
    upright: {
      keywords: "feeling trapped, self-doubt, restriction",
      meaning:  "Bound and blindfolded, but the ropes are loose: trapped mostly by your own thoughts.",
      past:     "You felt trapped and powerless.",
      present:  "You feel stuck, but most of the bars are in your head.",
      future:   "You'll feel boxed in. Remember there's a way out.",
      advice:   "Question the thought that says you can't.",
    },
    reversed: {
      keywords: "release, a new view, taking power back",
      meaning:  "Slipping the ropes: seeing your options and freeing yourself.",
      past:     "You freed yourself from something that boxed you in.",
      present:  "You're starting to see a way out.",
      future:   "You'll find your freedom.",
      advice:   "Take the first step. Nothing is actually stopping you.",
    },
  },
  {
    id: "swords-09",
    name: "Nine of Swords",
    suit: "swords",
    upright: {
      keywords: "anxiety, sleepless nights, worry",
      meaning:  "Awake at 3am: fear and guilt that loom larger in the dark than they really are.",
      past:     "Worry kept you up at night.",
      present:  "You're anxious, and your mind is making it worse.",
      future:   "A worrying time is ahead, but most of what you fear won't happen.",
      advice:   "Tell someone what's keeping you awake.",
    },
    reversed: {
      keywords: "worry easing, facing fears, reaching out",
      meaning:  "The morning after the bad night: fears shrinking as you face them or share them.",
      past:     "You came through a time of dread.",
      present:  "The worry is loosening its grip.",
      future:   "Your fears will turn out smaller than they looked.",
      advice:   "Let the fear go. It's had enough of your sleep.",
    },
  },
  {
    id: "swords-10",
    name: "Ten of Swords",
    suit: "swords",
    upright: {
      keywords: "rock bottom, a painful ending, defeat",
      meaning:  "The worst has happened, and it's over. The only way from here is up.",
      past:     "You hit rock bottom.",
      present:  "Something has ended badly. This is the lowest point.",
      future:   "A painful ending is coming, and after it, dawn.",
      advice:   "Accept that it's over, and stop reliving it.",
    },
    reversed: {
      keywords: "recovery, getting up, the worst behind you",
      meaning:  "Getting back up: the worst is over and healing has begun.",
      past:     "You survived the worst and started again.",
      present:  "You're recovering.",
      future:   "You'll rise from this.",
      advice:   "Get up. It's finished and you're still here.",
    },
  },
  {
    id: "swords-11",
    name: "Page of Swords",
    suit: "swords",
    upright: {
      keywords: "curiosity, sharp wits, watchfulness",
      meaning:  "Quick, curious and alert: hungry for information and full of questions.",
      past:     "You were hungry to learn and asked a lot of questions.",
      present:  "You're curious and watching closely.",
      future:   "News or a new idea will get your mind going.",
      advice:   "Ask the question, and find out more before deciding.",
    },
    reversed: {
      keywords: "gossip, all talk, cutting remarks",
      meaning:  "Wit without wisdom: gossip, snooping, saying more than you do.",
      past:     "There was gossip, or a lot of talk and little action.",
      present:  "You're saying more than you're doing.",
      future:   "Watch for gossip or a careless word.",
      advice:   "Think before you speak, and then actually do it.",
    },
  },
  {
    id: "swords-12",
    name: "Knight of Swords",
    suit: "swords",
    upright: {
      keywords: "ambition, directness, charging ahead",
      meaning:  "Racing straight at the goal: fast thinking, blunt speaking, no patience.",
      past:     "You charged at a goal with total focus.",
      present:  "You're moving fast and saying exactly what you think.",
      future:   "Things will move quickly and call for a quick decision.",
      advice:   "Be direct and go after it.",
    },
    reversed: {
      keywords: "recklessness, tactlessness, burnout",
      meaning:  "Speed without sense: rushing, cutting people with words, crashing.",
      past:     "You rushed in and said things you couldn't take back.",
      present:  "You're being hasty and a bit harsh.",
      future:   "A rash move or a sharp word could cause trouble.",
      advice:   "Slow down, and soften how you say it.",
    },
  },
  {
    id: "swords-13",
    name: "Queen of Swords",
    suit: "swords",
    upright: {
      keywords: "clear thinking, honesty, independence",
      meaning:  "Sees through nonsense and says so: fair, sharp and self-reliant.",
      past:     "Clear thinking and hard-won experience, yours or someone's, cut to the truth.",
      present:  "You see the situation exactly as it is.",
      future:   "You'll need a clear head and firm boundaries.",
      advice:   "Be honest and direct, and set the boundary.",
    },
    reversed: {
      keywords: "coldness, bitterness, harsh judgement",
      meaning:  "Sharpness turned cold: bitter, overly critical, shutting feeling out.",
      past:     "Hurt turned into coldness or harsh words.",
      present:  "You're being too hard on someone, or on yourself.",
      future:   "Guard against bitterness creeping in.",
      advice:   "Let some warmth back into how you see this.",
    },
  },
  {
    id: "swords-14",
    name: "King of Swords",
    suit: "swords",
    upright: {
      keywords: "authority, logic, fair judgement",
      meaning:  "The cool head in the room: reason, expertise, and decisions made on the facts.",
      past:     "A clear, fair judgement, yours or an authority's, decided things.",
      present:  "This needs your head, not your heart.",
      future:   "An expert opinion or a firm decision is coming.",
      advice:   "Decide with your head and stand by it.",
    },
    reversed: {
      keywords: "coldness, misuse of power, manipulation",
      meaning:  "Intellect used as a weapon: cold, controlling, twisting the facts.",
      past:     "Someone used their cleverness or authority unfairly.",
      present:  "Logic is being used to bully, or you're thinking this to death.",
      future:   "Watch for someone twisting the rules.",
      advice:   "Check that you're being fair, not just clever.",
    },
  },

  /* ---------- PENTACLES - money, craft, home ---------- */

  {
    id: "pentacles-01",
    name: "Ace of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "opportunity, a solid start, prosperity",
      meaning:  "A real, practical chance held out to you: a job, money, a seed worth planting.",
      past:     "A solid opportunity gave you your start.",
      present:  "You're being offered something real. Take it.",
      future:   "A new job, income or practical opportunity is coming.",
      advice:   "Plant the seed now.",
    },
    reversed: {
      keywords: "a missed chance, bad timing, shaky footing",
      meaning:  "An opportunity slipping away, or a start without solid ground under it.",
      past:     "A chance was missed, or a plan didn't pay off.",
      present:  "The timing or the money isn't right yet.",
      future:   "An offer may fall through. Have a back-up.",
      advice:   "Do your sums before you commit.",
    },
  },
  {
    id: "pentacles-02",
    name: "Two of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "juggling, adaptability, balance",
      meaning:  "Keeping two things in the air: balancing time, money and demands with a light touch.",
      past:     "You juggled a lot and kept it all going.",
      present:  "You're balancing several things at once, and managing.",
      future:   "You'll have to juggle priorities. Stay light on your feet.",
      advice:   "Stay flexible and keep things moving.",
    },
    reversed: {
      keywords: "overcommitted, dropping the ball, disorganised",
      meaning:  "One ball too many: stretched too thin, with things starting to slip.",
      past:     "You took on too much and something slipped.",
      present:  "You're overcommitted, and it's showing.",
      future:   "Something will have to give.",
      advice:   "Put one thing down before you drop it.",
    },
  },
  {
    id: "pentacles-03",
    name: "Three of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "teamwork, craft, learning",
      meaning:  "Skilled people building something together, and your work being noticed and valued.",
      past:     "You worked well with others and built something.",
      present:  "Your skills are needed and valued. Collaborate.",
      future:   "A joint project will bring out your best.",
      advice:   "Work with others, and listen to what they know.",
    },
    reversed: {
      keywords: "poor teamwork, sloppy work, feeling unvalued",
      meaning:  "A team pulling in different directions, or work that's careless or unappreciated.",
      past:     "A team effort fell apart, or your work wasn't valued.",
      present:  "You're not working well with the others.",
      future:   "A group project may hit friction.",
      advice:   "Either pull together or do it properly yourself.",
    },
  },
  {
    id: "pentacles-04",
    name: "Four of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "security, saving, holding on",
      meaning:  "Holding tight to what you have: careful, secure, maybe a little too guarded.",
      past:     "You held on tightly to what you had.",
      present:  "You're guarding what's yours, perhaps too closely.",
      future:   "You'll want to save and protect what you have.",
      advice:   "Be careful with your money, but don't let it own you.",
    },
    reversed: {
      keywords: "letting go, generosity, careless spending",
      meaning:  "The grip loosening: sharing more freely, or letting money run through your fingers.",
      past:     "You loosened your grip, or spent without thinking.",
      present:  "You're easing up on control.",
      future:   "You'll need to let go of something you've been clutching.",
      advice:   "Open your hand a little.",
    },
  },
  {
    id: "pentacles-05",
    name: "Five of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "hardship, worry, feeling left out",
      meaning:  "Out in the cold: money trouble, hard times, and not noticing the help close by.",
      past:     "You went through a hard, lean time.",
      present:  "You're feeling shut out and short of what you need.",
      future:   "A lean patch is ahead, but help will be nearer than it seems.",
      advice:   "Ask for help. There's a lit window right beside you.",
    },
    reversed: {
      keywords: "recovery, help arriving, coming in from the cold",
      meaning:  "Hard times ending: help accepted, and things slowly getting better.",
      past:     "You got through hardship and found your feet.",
      present:  "Things are starting to improve.",
      future:   "Help is on its way.",
      advice:   "Take the help that's offered.",
    },
  },
  {
    id: "pentacles-06",
    name: "Six of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "generosity, giving and receiving, fairness",
      meaning:  "Resources shared fairly: giving what you can, and accepting what you need.",
      past:     "Someone's generosity, maybe yours, made a difference.",
      present:  "You're in a position to give, or to receive. Do it gracefully.",
      future:   "Help or a gift is coming, or a chance to give one.",
      advice:   "Share what you have, and accept what's given.",
    },
    reversed: {
      keywords: "strings attached, one-sided giving, debt",
      meaning:  "Giving that isn't equal: favours with conditions, or always being the one who gives.",
      past:     "A gift came with strings, or you gave more than you got.",
      present:  "The give and take here isn't equal.",
      future:   "Be careful what you owe, and to whom.",
      advice:   "Check the terms before you accept, and stop over-giving.",
    },
  },
  {
    id: "pentacles-07",
    name: "Seven of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "patience, long-term effort, taking stock",
      meaning:  "Leaning on the hoe and looking at the crop: slow growth, and a pause to see how it's going.",
      past:     "You put in long, patient work.",
      present:  "You're waiting to see whether the effort pays off.",
      future:   "Results will come, slowly.",
      advice:   "Be patient. Check your progress and keep tending it.",
    },
    reversed: {
      keywords: "impatience, poor returns, wasted effort",
      meaning:  "A lot of work for a small harvest, and wondering whether to carry on.",
      past:     "You worked hard for little return.",
      present:  "You're frustrated at how slow this is.",
      future:   "The payoff may disappoint unless you change something.",
      advice:   "Ask whether this is still worth your effort.",
    },
  },
  {
    id: "pentacles-08",
    name: "Eight of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "practice, dedication, craft",
      meaning:  "Head down at the bench, making the same thing a little better each time.",
      past:     "You put in the hours and built real skill.",
      present:  "You're hard at work, getting better with every piece.",
      future:   "A period of focused work or study is ahead.",
      advice:   "Keep practising. Do it again, better.",
    },
    reversed: {
      keywords: "perfectionism, going through the motions, shortcuts",
      meaning:  "Work without heart: endless fiddling, or cutting corners because you've lost interest.",
      past:     "You lost interest in the work, or fussed over details.",
      present:  "You're busy but not improving.",
      future:   "The work will feel like a grind for a while.",
      advice:   "Remember why you're doing this, or do something else.",
    },
  },
  {
    id: "pentacles-09",
    name: "Nine of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "independence, comfort, earned reward",
      meaning:  "A garden you grew yourself: comfort and freedom earned by your own effort.",
      past:     "You built a comfortable, independent life.",
      present:  "You've earned this. Enjoy it.",
      future:   "Self-sufficiency and ease are coming.",
      advice:   "Treat yourself. You paid for it.",
    },
    reversed: {
      keywords: "overwork, hollow success, dependence",
      meaning:  "The garden without the pleasure: working too hard to enjoy it, or leaning on others for security.",
      past:     "You worked so hard that you forgot to enjoy any of it.",
      present:  "You have the comfort but not the contentment.",
      future:   "Money worries, or leaning too much on someone, may crop up.",
      advice:   "Stop working long enough to enjoy what you've made.",
    },
  },
  {
    id: "pentacles-10",
    name: "Ten of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "lasting security, family, legacy",
      meaning:  "Wealth that lasts: home, family, something built to be handed on.",
      past:     "Family and solid foundations gave you your start.",
      present:  "You're well established, with roots.",
      future:   "Long-term security is ahead.",
      advice:   "Think long term and build something that lasts.",
    },
    reversed: {
      keywords: "family strain, money disputes, short-term thinking",
      meaning:  "Cracks in the foundation: quarrels over money or family, or security that doesn't last.",
      past:     "There was strain over family or money.",
      present:  "Something you thought was secure isn't.",
      future:   "A family or money matter will need sorting out.",
      advice:   "Sort out the practical details before they become a quarrel.",
    },
  },
  {
    id: "pentacles-11",
    name: "Page of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "study, a practical plan, a new skill",
      meaning:  "The keen student: learning something useful and taking the first steps of a plan.",
      past:     "You set out to learn something practical.",
      present:  "You're at the start of something you can build on.",
      future:   "A chance to study, or a small solid opportunity, is coming.",
      advice:   "Start small and learn it properly.",
    },
    reversed: {
      keywords: "procrastination, lack of focus, a wasted chance",
      meaning:  "Good intentions and no follow-through: putting it off, getting distracted.",
      past:     "You put off something you meant to learn.",
      present:  "You're not following through.",
      future:   "A plan will stall unless you commit.",
      advice:   "Stop planning and do the first small thing.",
    },
  },
  {
    id: "pentacles-12",
    name: "Knight of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "hard work, reliability, routine",
      meaning:  "Slow and steady: showing up every day and getting it done.",
      past:     "You plodded steadily on, and it worked.",
      present:  "You're making slow, reliable progress.",
      future:   "Steady work will get you there, without shortcuts.",
      advice:   "Keep to the routine.",
    },
    reversed: {
      keywords: "stuck in a rut, boredom, laziness",
      meaning:  "Routine gone stale: plodding without purpose, or not bothering at all.",
      past:     "You got stuck in a rut.",
      present:  "You're bored, or doing the bare minimum.",
      future:   "Things will stagnate unless you shake up the routine.",
      advice:   "Change something small today.",
    },
  },
  {
    id: "pentacles-13",
    name: "Queen of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "nurturing, practicality, comfort",
      meaning:  "Warm, practical and generous: someone who makes a home and looks after everyone in it.",
      past:     "Practical care, yours or someone's, kept everything running.",
      present:  "You're looking after things well, people included.",
      future:   "A comfortable, well-tended time is coming.",
      advice:   "Take care of the practical things, and of your body.",
    },
    reversed: {
      keywords: "self-neglect, work and home out of balance, smothering",
      meaning:  "Caring for everyone but yourself, with work and home pulling against each other.",
      past:     "You looked after everyone except yourself.",
      present:  "Work and home are out of balance.",
      future:   "You'll feel stretched between duties.",
      advice:   "Put yourself on your own to-do list.",
    },
  },
  {
    id: "pentacles-14",
    name: "King of Pentacles",
    suit: "pentacles",
    upright: {
      keywords: "success, security, generosity",
      meaning:  "Built it and shares it: prosperous, dependable, good with the material world.",
      past:     "Steady success, yours or a provider's, gave you security.",
      present:  "You've built something solid, and you can afford to be generous.",
      future:   "Material success and stability are coming.",
      advice:   "Run it like a business, and be generous with what it earns.",
    },
    reversed: {
      keywords: "greed, stubbornness, money over meaning",
      meaning:  "Success gone stale: obsessed with money, stubborn, mean with it.",
      past:     "Money or stubbornness got in the way.",
      present:  "You're too focused on what things cost.",
      future:   "Watch for a bad investment or a tight-fisted figure.",
      advice:   "Remember what the money is for.",
    },
  },
];
